name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    name: Package build    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore src\Demo.Lib.sln

      - name: Build Solution
        run: |
          msbuild.exe src\Demo.Lib.sln /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run Tests for Core
        run: dotnet test .\test\Demo.Lib.Core.Test\Demo.Lib.Core.Test.csproj /p:CollectCoverage=true /p:Threshold=80

      - name: Run Tests for v7
        run: dotnet test .\test\Demo.Lib.v7.Test\Demo.Lib.v7.Test.csproj /p:CollectCoverage=true /p:Threshold=80 /p:Exclude=[Demo.Lib.Core]*
